[Fix] - Fix pipeline config

diff --git a/.github/workflows/test-fluent-bit.yml b/.github/workflows/test-fluent-bit.yml
--- a/.github/workflows/test-fluent-bit.yml
+++ b/.github/workflows/test-fluent-bit.yml
@@ -9,7 +9,7 @@ on:
 jobs:
   test-fluent-bit-parser:
     runs-on: ubuntu-latest
-    timeout-minutes: 5  # หยุด workflow หลัง 5 นาทีถ้ายังไม่จบ
+    timeout-minutes: 5
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -30,3 +30,8 @@ jobs:
       - name: Run Fluent Bit and Pipe to Python
         run: |
           docker run --rm -v $(pwd)/csv:/csv -v $(pwd)/conf:/conf fluent/fluent-bit:latest /fluent-bit/bin/fluent-bit -c /conf/fluent-bit.conf --once | python read_from_stdin.py
+          # Check exit codes
+          if [ ${PIPESTATUS[0]} -ne 0 ] || [ ${PIPESTATUS[1]} -ne 0 ]; then
+            echo "Fluent Bit or Python failed"
+            exit 1
+          fi
